import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { User } from '../../users/user.entity';
import { AgentConnection } from './agent-connection.entity';

export enum CandidateStatus {
  PendingReview = 'pending_review',
  Approved = 'approved',
  Rejected = 'rejected',
  Contacted = 'contacted',
}

@Entity('match_candidates')
export class MatchCandidate {
  @PrimaryGeneratedColumn()
  id: number;

  /** The user who OWNS this recommendation (the agent's principal) */
  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: User;

  @Column()
  userId: number;

  /** The agent that generated this recommendation */
  @ManyToOne(() => AgentConnection, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'agentConnectionId' })
  agentConnection: AgentConnection | null;

  @Column({ type: 'int', nullable: true })
  agentConnectionId: number | null;

  /** The recommended counterpart */
  @Column()
  candidateUserId: number;

  /** 0.0 – 1.0 composite match score */
  @Column({ type: 'float', default: 0 })
  score: number;

  /**
   * Short machine-generated reason tags, e.g.
   * ["same_city", "similar_training_schedule", "compatible_relationship_goal"]
   */
  @Column({ type: 'jsonb', default: '[]' })
  reasonTags: string[];

  /** Human-readable explanation generated by the agent */
  @Column({ type: 'text', default: '' })
  reasonText: string;

  @Column({
    type: 'enum',
    enum: CandidateStatus,
    default: CandidateStatus.PendingReview,
  })
  status: CandidateStatus;

  /** Feedback the user gave after reviewing */
  @Column({ type: 'text', nullable: true })
  userFeedback: string | null;

  @CreateDateColumn()
  createdAt: Date;
}
