import { MigrationInterface, QueryRunner } from 'typeorm';

export class CoreBaseline1780000000000 implements MigrationInterface {
  name = 'CoreBaseline1780000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const statements = [
      `CREATE TABLE "users" (
        "id" SERIAL PRIMARY KEY,
        "email" varchar NOT NULL UNIQUE,
        "password" varchar NOT NULL,
        "phone" varchar UNIQUE,
        "wechatOpenId" varchar,
        "name" varchar NOT NULL,
        "avatar" varchar NOT NULL DEFAULT '',
        "color" varchar NOT NULL DEFAULT '#C8FF00',
        "gender" varchar NOT NULL DEFAULT '',
        "age" integer NOT NULL DEFAULT 0,
        "city" varchar NOT NULL DEFAULT '',
        "lat" double precision,
        "lng" double precision,
        "locationUpdatedAt" timestamptz,
        "acceptNearbyMatch" boolean NOT NULL DEFAULT true,
        "gym" varchar NOT NULL DEFAULT '',
        "bio" text NOT NULL DEFAULT '',
        "coverUrl" varchar,
        "singleCert" boolean NOT NULL DEFAULT false,
        "verified" boolean NOT NULL DEFAULT false,
        "interestTags" text NOT NULL DEFAULT '',
        "trainingDays" integer NOT NULL DEFAULT 0,
        "trainingCount" integer NOT NULL DEFAULT 0,
        "caloriesBurned" integer NOT NULL DEFAULT 0,
        "bestRecords" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "trustScore" integer NOT NULL DEFAULT 0,
        "socialTrustCount" integer NOT NULL DEFAULT 0,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "user_social_profiles" (
        "userId" integer PRIMARY KEY REFERENCES "users"("id") ON DELETE CASCADE,
        "gender" varchar NOT NULL DEFAULT '',
        "nickname" varchar NOT NULL DEFAULT '',
        "ageRange" varchar NOT NULL DEFAULT '',
        "city" varchar NOT NULL DEFAULT '',
        "zodiac" varchar NOT NULL DEFAULT '',
        "mbti" varchar NOT NULL DEFAULT '',
        "traits" text NOT NULL DEFAULT '',
        "socialStyle" varchar NOT NULL DEFAULT '',
        "communicationStyle" varchar NOT NULL DEFAULT '',
        "nearbyArea" varchar NOT NULL DEFAULT '',
        "fitnessGoals" text NOT NULL DEFAULT '',
        "interestTags" text NOT NULL DEFAULT '',
        "lifestyleTags" text NOT NULL DEFAULT '',
        "socialScenes" text NOT NULL DEFAULT '',
        "wantToMeet" text NOT NULL DEFAULT '',
        "preferredTraits" text NOT NULL DEFAULT '',
        "avoidTraits" text NOT NULL DEFAULT '',
        "relationshipGoals" text NOT NULL DEFAULT '',
        "openness" varchar NOT NULL DEFAULT '',
        "availableTimes" text NOT NULL DEFAULT '',
        "weekdayAvailability" varchar NOT NULL DEFAULT '',
        "weekendAvailability" varchar NOT NULL DEFAULT '',
        "socialPreference" varchar NOT NULL DEFAULT '',
        "rejectRules" varchar NOT NULL DEFAULT '',
        "privacyBoundary" varchar NOT NULL DEFAULT '',
        "profileDiscoverable" boolean NOT NULL DEFAULT false,
        "agentCanRecommendMe" boolean NOT NULL DEFAULT false,
        "agentCanStartChatAfterApproval" boolean NOT NULL DEFAULT false,
        "hideSensitiveTags" boolean NOT NULL DEFAULT true,
        "aiSummary" text NOT NULL DEFAULT '',
        "aiProfileCard" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "matchSignals" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "sensitiveTagDecisions" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "follows" (
        "id" SERIAL PRIMARY KEY,
        "followerId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "followingId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_follows_pair" UNIQUE ("followerId", "followingId")
      )`,
      `CREATE TABLE "meets" (
        "id" SERIAL PRIMARY KEY,
        "title" varchar NOT NULL,
        "type" varchar NOT NULL,
        "sport" varchar NOT NULL,
        "time" varchar NOT NULL,
        "loc" varchar NOT NULL,
        "address" varchar NOT NULL DEFAULT '',
        "poiId" varchar,
        "lat" double precision,
        "lng" double precision,
        "dist" varchar NOT NULL DEFAULT '',
        "price" varchar NOT NULL DEFAULT '免费',
        "slots" integer NOT NULL DEFAULT 0,
        "maxSlots" integer NOT NULL DEFAULT 4,
        "level" varchar NOT NULL DEFAULT '全部',
        "desc" text NOT NULL DEFAULT '',
        "feeType" varchar,
        "groupType" varchar,
        "creatorType" varchar,
        "status" varchar NOT NULL DEFAULT 'pending',
        "tripShareToken" varchar,
        "activityId" integer,
        "rating" numeric(3,1) NOT NULL DEFAULT 0,
        "meetCount" integer NOT NULL DEFAULT 0,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "city" varchar NOT NULL DEFAULT '',
        "startAt" timestamp,
        "autoCancelAt" timestamp,
        "cancelReason" varchar,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "meet_participants" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "meetId" integer NOT NULL REFERENCES "meets"("id") ON DELETE CASCADE,
        "status" varchar NOT NULL DEFAULT 'pending',
        "tripShareToken" varchar,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_meet_participants_user_meet" UNIQUE ("userId", "meetId")
      )`,
      `CREATE TABLE "agent_connections" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentName" varchar NOT NULL DEFAULT 'custom',
        "agentDisplayName" varchar NOT NULL DEFAULT '',
        "agentWebhookUrl" varchar,
        "agentTokenHash" varchar NOT NULL,
        "tokenPrefix" varchar(12) NOT NULL,
        "permissionLevel" varchar NOT NULL DEFAULT 'open',
        "status" varchar NOT NULL DEFAULT 'active',
        "dailyActionLimit" integer NOT NULL DEFAULT 50,
        "dailyActionsUsed" integer NOT NULL DEFAULT 0,
        "dailyResetAt" timestamptz,
        "lastActiveAt" timestamptz,
        "expiresAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_profiles" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer REFERENCES "agent_connections"("id") ON DELETE SET NULL,
        "agentName" varchar(80) NOT NULL,
        "agentType" varchar NOT NULL DEFAULT 'user_agent',
        "provider" varchar NOT NULL DEFAULT 'custom',
        "avatar" varchar NOT NULL DEFAULT '',
        "bio" text NOT NULL DEFAULT '',
        "personality" text NOT NULL DEFAULT '',
        "goals" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "interests" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "preferredTargets" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "boundaries" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "autonomyLevel" varchar NOT NULL DEFAULT 'normal',
        "status" varchar NOT NULL DEFAULT 'active',
        "lastActiveAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_permissions" (
        "id" SERIAL PRIMARY KEY,
        "agentConnectionId" integer NOT NULL REFERENCES "agent_connections"("id") ON DELETE CASCADE,
        "action" varchar NOT NULL,
        "granted" boolean NOT NULL DEFAULT true,
        "constraints" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "grantedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_settings" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer,
        "mode" varchar NOT NULL DEFAULT 'balanced',
        "allowSearch" boolean NOT NULL DEFAULT true,
        "allowDraftMessage" boolean NOT NULL DEFAULT true,
        "allowSendMessage" boolean NOT NULL DEFAULT true,
        "allowAutoReply" boolean NOT NULL DEFAULT true,
        "allowCreateActivity" boolean NOT NULL DEFAULT true,
        "allowJoinActivity" boolean NOT NULL DEFAULT true,
        "allowShareLocation" boolean NOT NULL DEFAULT true,
        "allowUploadProof" boolean NOT NULL DEFAULT true,
        "allowContactExchange" boolean NOT NULL DEFAULT true,
        "dailyActionLimit" integer NOT NULL DEFAULT 20,
        "requireApprovalForFirstMessage" boolean NOT NULL DEFAULT false,
        "requireApprovalForOfflineMeeting" boolean NOT NULL DEFAULT false,
        "requireApprovalForPhotoUpload" boolean NOT NULL DEFAULT false,
        "requireApprovalForAll" boolean NOT NULL DEFAULT false,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_agent_settings_user_connection" UNIQUE ("userId", "agentConnectionId")
      )`,
      `CREATE TABLE "user_preferences" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "bio" text NOT NULL DEFAULT '',
        "interests" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "boundaries" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "privacyMode" varchar NOT NULL DEFAULT 'private',
        "chatStyle" varchar NOT NULL DEFAULT 'warm',
        "availability" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "allowAgentDiscovery" boolean NOT NULL DEFAULT false,
        "allowPublicProfile" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "user_social_requests" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentId" integer REFERENCES "agent_connections"("id") ON DELETE SET NULL,
        "source" varchar NOT NULL DEFAULT 'manual',
        "type" varchar NOT NULL DEFAULT 'custom',
        "title" varchar(200) NOT NULL DEFAULT '',
        "description" text NOT NULL DEFAULT '',
        "rawText" text NOT NULL DEFAULT '',
        "city" varchar(100) NOT NULL DEFAULT '',
        "lat" double precision,
        "lng" double precision,
        "radiusKm" integer NOT NULL DEFAULT 5,
        "timeStart" timestamptz,
        "timeEnd" timestamptz,
        "genderPreference" varchar NOT NULL DEFAULT 'any',
        "ageMin" integer,
        "ageMax" integer,
        "interestTags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "activityType" varchar(100) NOT NULL DEFAULT '',
        "safetyRequirement" varchar NOT NULL DEFAULT 'none',
        "agentAllowed" boolean NOT NULL DEFAULT true,
        "requireUserConfirmation" boolean NOT NULL DEFAULT true,
        "status" varchar NOT NULL DEFAULT 'draft',
        "visibility" varchar NOT NULL DEFAULT 'matched_only',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "expiresAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_request_candidates" (
        "id" SERIAL PRIMARY KEY,
        "socialRequestId" integer NOT NULL REFERENCES "user_social_requests"("id") ON DELETE CASCADE,
        "candidateUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "score" integer NOT NULL,
        "level" varchar NOT NULL DEFAULT 'medium',
        "scoreBreakdown" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "reasons" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "commonTags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "distanceKm" double precision,
        "riskLevel" varchar NOT NULL DEFAULT 'low',
        "riskWarnings" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "suggestedMessage" text NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT 'suggested',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "uniq_src_request_candidate_user" UNIQUE ("socialRequestId", "candidateUserId")
      )`,
      `CREATE TABLE "social_requests" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer,
        "requestType" varchar NOT NULL,
        "title" varchar NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "city" varchar NOT NULL DEFAULT '',
        "loc" varchar NOT NULL DEFAULT '',
        "lat" double precision,
        "lng" double precision,
        "radiusKm" integer NOT NULL DEFAULT 5,
        "timePreference" varchar NOT NULL DEFAULT '',
        "visibility" varchar NOT NULL DEFAULT 'matched_users_only',
        "status" varchar NOT NULL DEFAULT 'searching',
        "requiresUserConfirmation" boolean NOT NULL DEFAULT true,
        "filters" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "candidateUserIds" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "matchedCount" integer NOT NULL DEFAULT 0,
        "riskLevel" varchar NOT NULL DEFAULT 'low',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "public_social_intents" (
        "id" varchar(80) PRIMARY KEY,
        "userId" integer,
        "linkedSocialRequestId" integer,
        "source" varchar NOT NULL DEFAULT 'public_intent',
        "mode" varchar NOT NULL DEFAULT 'public',
        "requestType" varchar NOT NULL,
        "title" varchar NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "interestTags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "city" varchar NOT NULL DEFAULT '',
        "loc" varchar NOT NULL DEFAULT '',
        "lat" double precision,
        "lng" double precision,
        "radiusKm" integer NOT NULL DEFAULT 5,
        "timePreference" varchar NOT NULL DEFAULT '',
        "locationPreference" text NOT NULL DEFAULT '',
        "socialGoal" text NOT NULL DEFAULT '',
        "riskLevel" varchar NOT NULL DEFAULT 'low',
        "requiresUserConfirmation" boolean NOT NULL DEFAULT true,
        "filters" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "candidateUserIds" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "matchedCount" integer NOT NULL DEFAULT 0,
        "status" varchar NOT NULL DEFAULT 'searching',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "match_candidates" (
        "id" SERIAL PRIMARY KEY,
        "requestId" integer NOT NULL,
        "targetUserId" integer,
        "agentConnectionId" integer NOT NULL,
        "score" double precision NOT NULL DEFAULT 0,
        "reasons" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "introMessage" text NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT 'pending',
        "rejectionReason" text,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_tasks" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer REFERENCES "agent_connections"("id") ON DELETE SET NULL,
        "taskType" varchar(80) NOT NULL DEFAULT 'social_goal',
        "title" varchar(200) NOT NULL DEFAULT '',
        "goal" text NOT NULL DEFAULT '',
        "input" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "plan" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "toolCalls" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "result" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "memory" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "status" varchar NOT NULL DEFAULT 'pending',
        "permissionMode" varchar NOT NULL DEFAULT 'confirm',
        "riskLevel" varchar NOT NULL DEFAULT 'low',
        "idempotencyKey" varchar(120),
        "statusReason" text,
        "error" jsonb,
        "startedAt" timestamptz,
        "awaitingConfirmationAt" timestamptz,
        "completedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_task_events" (
        "id" SERIAL PRIMARY KEY,
        "taskId" integer NOT NULL REFERENCES "agent_tasks"("id") ON DELETE CASCADE,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "eventType" varchar NOT NULL,
        "actor" varchar NOT NULL DEFAULT 'agent',
        "summary" varchar(500) NOT NULL DEFAULT '',
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_run_checkpoints" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "taskId" integer NOT NULL REFERENCES "agent_tasks"("id") ON DELETE CASCADE,
        "runId" integer,
        "parentCheckpointId" integer,
        "type" varchar NOT NULL DEFAULT 'step',
        "status" varchar NOT NULL DEFAULT 'open',
        "approvalId" varchar(120),
        "stepId" varchar(120),
        "toolName" varchar(80),
        "branchId" varchar(120),
        "traceId" varchar(120),
        "summary" text NOT NULL DEFAULT '',
        "snapshot" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "actions" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "result" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "messages" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "retryCount" integer NOT NULL DEFAULT 0,
        "replayCount" integer NOT NULL DEFAULT 0,
        "forkCount" integer NOT NULL DEFAULT 0,
        "version" integer NOT NULL DEFAULT 0,
        "closedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_approval_requests" (
        "id" SERIAL PRIMARY KEY,
        "agentConnectionId" integer REFERENCES "agent_connections"("id") ON DELETE SET NULL,
        "agentTaskId" integer REFERENCES "agent_tasks"("id") ON DELETE SET NULL,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "type" varchar NOT NULL,
        "actionType" varchar(80) NOT NULL DEFAULT '',
        "skillName" varchar(64) NOT NULL DEFAULT '',
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "summary" varchar(500) NOT NULL DEFAULT '',
        "reason" text NOT NULL DEFAULT '',
        "createdBy" varchar(32) NOT NULL DEFAULT 'agent',
        "relatedSocialRequestId" integer,
        "relatedCandidateId" integer,
        "relatedActivityId" integer,
        "riskLevel" varchar NOT NULL DEFAULT 'medium',
        "status" varchar NOT NULL DEFAULT 'pending',
        "agentRationale" text NOT NULL DEFAULT '',
        "expiresAt" timestamptz NOT NULL,
        "respondedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_side_effect_ledger" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL,
        "agentTaskId" integer,
        "actionType" varchar(96) NOT NULL,
        "idempotencyKey" varchar(180) NOT NULL,
        "status" varchar NOT NULL DEFAULT 'pending',
        "resourceType" varchar(80) NOT NULL DEFAULT '',
        "resourceId" varchar(120) NOT NULL DEFAULT '',
        "attemptCount" integer NOT NULL DEFAULT 0,
        "result" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "errorMessage" text NOT NULL DEFAULT '',
        "lastAttemptAt" timestamptz,
        "nextRetryAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_runs" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentTaskId" integer,
        "agentName" varchar(120) NOT NULL DEFAULT 'fitmeet_social_agent',
        "permissionMode" varchar NOT NULL DEFAULT 'assist',
        "status" varchar NOT NULL DEFAULT 'running',
        "userMessage" text NOT NULL,
        "safeSummary" text NOT NULL DEFAULT '',
        "resultPayload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "completedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_run_steps" (
        "id" SERIAL PRIMARY KEY,
        "runId" integer NOT NULL,
        "userId" integer NOT NULL,
        "stepOrder" integer NOT NULL,
        "stepKey" varchar(120) NOT NULL,
        "title" varchar(200) NOT NULL,
        "status" varchar NOT NULL DEFAULT 'running',
        "toolName" varchar(120),
        "requiresUserConfirmation" boolean NOT NULL DEFAULT false,
        "safePayload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_tool_calls" (
        "id" SERIAL PRIMARY KEY,
        "runId" integer NOT NULL,
        "userId" integer NOT NULL,
        "stepId" integer,
        "toolName" varchar(120) NOT NULL,
        "status" varchar NOT NULL DEFAULT 'running',
        "requiresUserConfirmation" boolean NOT NULL DEFAULT false,
        "safeInput" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "safeOutput" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "errorCode" varchar(80),
        "errorMessage" text,
        "durationMs" integer,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_messages" (
        "id" SERIAL PRIMARY KEY,
        "runId" integer NOT NULL,
        "userId" integer NOT NULL,
        "role" varchar(20) NOT NULL,
        "messageType" varchar(40) NOT NULL DEFAULT 'text',
        "content" text NOT NULL,
        "safeMetadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_memory_updates" (
        "id" SERIAL PRIMARY KEY,
        "runId" integer NOT NULL,
        "userId" integer NOT NULL,
        "memoryType" varchar(80) NOT NULL,
        "source" varchar(120) NOT NULL,
        "safePayload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "requiresUserConfirmation" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_activity_logs" (
        "id" SERIAL PRIMARY KEY,
        "agentConnectionId" integer,
        "userId" integer NOT NULL,
        "targetUserId" integer,
        "action" varchar NOT NULL,
        "actionType" varchar(100),
        "skillName" varchar(64),
        "requestId" varchar(64),
        "riskLevel" varchar(40),
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "result" varchar NOT NULL DEFAULT 'success',
        "riskScore" double precision NOT NULL DEFAULT 0,
        "errorMessage" text,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_action_logs" (
        "id" SERIAL PRIMARY KEY,
        "agentId" integer,
        "agentTaskId" integer,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "actionType" varchar NOT NULL,
        "skillName" varchar(100),
        "requestId" varchar(64),
        "traceId" varchar(64),
        "riskLevel" varchar(40),
        "actionStatus" varchar NOT NULL DEFAULT 'pending_approval',
        "targetUserId" integer,
        "relatedSocialRequestId" integer,
        "relatedCandidateId" integer,
        "relatedActivityId" integer,
        "relatedApprovalId" integer,
        "inputSummary" varchar(500),
        "outputSummary" varchar(500),
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "reason" text,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_agent_long_term_memory" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
        "preferenceMemory" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "safetyMemory" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "relationshipMemory" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "activityMemory" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "recentHighlights" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "version" integer NOT NULL DEFAULT 0,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_agent_message_feedback" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentTaskId" integer,
        "messageId" varchar(160) NOT NULL,
        "rating" varchar(20) NOT NULL,
        "reason" varchar(240),
        "traceId" varchar(120),
        "runId" varchar(120),
        "source" varchar(80) NOT NULL DEFAULT 'agent_web',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_agent_reminder_preferences" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
        "enabled" boolean NOT NULL DEFAULT false,
        "frequency" varchar NOT NULL DEFAULT 'weekly',
        "quietStart" varchar(16) NOT NULL DEFAULT '09:00',
        "quietEnd" varchar(16) NOT NULL DEFAULT '21:00',
        "tone" varchar(24) NOT NULL DEFAULT 'gentle',
        "rules" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "lastSentAt" timestamptz,
        "nextRunAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_agent_reminders" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "kind" varchar(40) NOT NULL,
        "status" varchar(40) NOT NULL DEFAULT 'suggested',
        "title" varchar(160) NOT NULL,
        "summary" varchar(220) NOT NULL,
        "body" text NOT NULL,
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "dedupeKey" varchar(120),
        "agentTaskId" integer,
        "scheduledFor" timestamptz,
        "openedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_agent_user_interest_events" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "targetUserId" integer,
        "eventType" varchar(40) NOT NULL,
        "agentTaskId" integer,
        "socialRequestId" integer,
        "candidateId" integer,
        "publicIntentId" integer,
        "weight" double precision NOT NULL DEFAULT 1,
        "tags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "reasons" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "source" varchar(120),
        "dedupeKey" varchar(160),
        "traceId" varchar(120),
        "channel" varchar(80) NOT NULL DEFAULT 'agent_web',
        "note" varchar(240),
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_profiles" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
        "completeness" integer NOT NULL DEFAULT 0,
        "summary" text NOT NULL DEFAULT '',
        "privateSummary" text NOT NULL DEFAULT '',
        "locale" varchar NOT NULL DEFAULT 'zh-CN',
        "city" varchar NOT NULL DEFAULT '',
        "timezone" varchar NOT NULL DEFAULT 'Asia/Shanghai',
        "lastExtractedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_fields" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "category" varchar(64) NOT NULL,
        "fieldKey" varchar(96) NOT NULL,
        "value" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "source" varchar(48) NOT NULL,
        "confidence" double precision NOT NULL DEFAULT 1,
        "sensitive" boolean NOT NULL DEFAULT false,
        "visibleToUser" boolean NOT NULL DEFAULT true,
        "requiresConfirmation" boolean NOT NULL DEFAULT false,
        "confirmedAt" timestamptz,
        "revokedAt" timestamptz,
        "status" varchar NOT NULL DEFAULT 'active',
        "editable" boolean NOT NULL DEFAULT true,
        "isDeleted" boolean NOT NULL DEFAULT false,
        "availableForMatching" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_life_graph_fields_user_category_key" UNIQUE ("userId", "category", "fieldKey")
      )`,
      `CREATE TABLE "life_graph_proposals" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentTaskId" integer,
        "proposalKey" varchar(96),
        "fields" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "status" varchar NOT NULL DEFAULT 'pending',
        "reason" text NOT NULL DEFAULT '',
        "sourceEvents" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "requiresUserConfirmation" boolean NOT NULL DEFAULT true,
        "confirmedAt" timestamptz,
        "rejectedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_audit_logs" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "fieldKey" varchar(96) NOT NULL,
        "action" varchar(64) NOT NULL,
        "beforeValue" jsonb,
        "afterValue" jsonb,
        "source" varchar(48) NOT NULL,
        "confidence" double precision,
        "riskLevel" varchar(48) NOT NULL,
        "reason" text NOT NULL DEFAULT '',
        "actorUserId" integer,
        "traceId" varchar(96),
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_events" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "eventType" varchar(64) NOT NULL,
        "source" varchar(80),
        "agentTaskId" integer,
        "socialRequestId" integer,
        "candidateId" integer,
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "summary" text NOT NULL DEFAULT '',
        "weight" double precision NOT NULL DEFAULT 1,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_corrections" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "category" varchar(48) NOT NULL,
        "fieldKey" varchar(80),
        "oldValueHash" varchar(64),
        "newValueHash" varchar(96),
        "note" text NOT NULL DEFAULT '',
        "beforeValue" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "afterValue" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "applied" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_signal_scores" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "signalKey" varchar(80) NOT NULL,
        "score" double precision NOT NULL DEFAULT 50,
        "confidence" double precision NOT NULL DEFAULT 0.5,
        "model" varchar(80) NOT NULL DEFAULT 'rules_v1',
        "explanation" text NOT NULL DEFAULT '',
        "evidence" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "visible" boolean NOT NULL DEFAULT true,
        "version" integer NOT NULL DEFAULT 0,
        "lastComputedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_life_graph_signal_scores_user_key" UNIQUE ("userId", "signalKey")
      )`,
      `CREATE TABLE "life_graph_update_audits" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "updateType" varchar(80) NOT NULL,
        "source" varchar(80) NOT NULL DEFAULT 'life_graph',
        "status" varchar(40) NOT NULL,
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "result" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "reason" text NOT NULL DEFAULT '',
        "requiresConfirmation" boolean NOT NULL DEFAULT true,
        "proposalId" integer,
        "agentTaskId" integer,
        "confirmedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_security_requests" (
        "id" SERIAL PRIMARY KEY,
        "requestType" varchar(20) NOT NULL,
        "status" varchar(40) NOT NULL DEFAULT 'pending_cooldown',
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "requestKey" varchar(128) NOT NULL,
        "availableAt" timestamptz NOT NULL,
        "expiresAt" timestamptz NOT NULL,
        "confirmedAt" timestamptz,
        "cancelledAt" timestamptz,
        "reason" varchar(160),
        "deliveryStatus" varchar(40) NOT NULL DEFAULT 'skipped',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "life_graph_access_audit_logs" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "actorUserId" integer,
        "action" varchar(80) NOT NULL,
        "resource" varchar(120) NOT NULL DEFAULT '',
        "purpose" varchar(180) NOT NULL DEFAULT '',
        "decision" varchar(40) NOT NULL DEFAULT 'allowed',
        "fieldKeys" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "riskFlags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "social_activities" (
        "id" SERIAL PRIMARY KEY,
        "creatorId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "participantIds" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "socialRequestId" integer,
        "candidateId" integer,
        "meetId" integer,
        "type" varchar NOT NULL DEFAULT 'custom',
        "title" varchar(200) NOT NULL DEFAULT '',
        "description" text NOT NULL DEFAULT '',
        "locationName" varchar(200) NOT NULL DEFAULT '',
        "city" varchar(100) NOT NULL DEFAULT '',
        "lat" double precision,
        "lng" double precision,
        "startAt" timestamp,
        "endAt" timestamp,
        "status" varchar NOT NULL DEFAULT 'draft',
        "publicSafetyTips" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "requiredProofs" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "visible" boolean NOT NULL DEFAULT true,
        "privacyMode" varchar NOT NULL DEFAULT 'matched_only',
        "trustLevel" varchar NOT NULL DEFAULT 'normal',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "safetyContext" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "proofSummary" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "cancelReason" text,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "activity_proofs" (
        "id" SERIAL PRIMARY KEY,
        "activityId" integer NOT NULL REFERENCES "social_activities"("id") ON DELETE CASCADE,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "proofType" varchar NOT NULL,
        "photoUrl" varchar(500),
        "note" varchar(500) NOT NULL DEFAULT '',
        "locationApprox" varchar(200) NOT NULL DEFAULT '',
        "privacyMode" varchar NOT NULL DEFAULT 'private',
        "status" varchar NOT NULL DEFAULT 'pending',
        "reviewerId" integer,
        "reviewedAt" timestamptz,
        "reviewNote" varchar(500) NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "activity_templates" (
        "id" SERIAL PRIMARY KEY,
        "type" varchar NOT NULL UNIQUE,
        "title" varchar(200) NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "defaultDurationMinutes" integer NOT NULL DEFAULT 30,
        "safetyTips" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "requiredProofs" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "suggestedLocations" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "riskLevel" varchar NOT NULL DEFAULT 'low',
        "active" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "safety_events" (
        "id" SERIAL PRIMARY KEY,
        "agentConnectionId" integer,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "type" varchar NOT NULL,
        "severity" varchar NOT NULL DEFAULT 'low',
        "description" text NOT NULL DEFAULT '',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "resolved" boolean NOT NULL DEFAULT false,
        "resolutionNote" text,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "contact_requests" (
        "id" SERIAL PRIMARY KEY,
        "requesterId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "targetUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer,
        "status" varchar NOT NULL DEFAULT 'pending',
        "note" text NOT NULL DEFAULT '',
        "expiresAt" timestamptz NOT NULL,
        "respondedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "payment_intents" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "agentConnectionId" integer,
        "agentTaskId" integer,
        "provider" varchar(80),
        "providerPaymentId" integer,
        "amount" numeric(12,2) NOT NULL,
        "currency" varchar(8) NOT NULL DEFAULT 'CNY',
        "description" text NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT 'pending',
        "source" varchar(80) NOT NULL DEFAULT 'manual_intent',
        "traceId" varchar(120),
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "emergency_contacts" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "name" varchar NOT NULL,
        "phone" varchar NOT NULL,
        "relationship" varchar NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "safety_reports" (
        "id" SERIAL PRIMARY KEY,
        "reporterId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "reportedUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "type" varchar NOT NULL,
        "reason" varchar NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT 'pending',
        "resolution" text NOT NULL DEFAULT '',
        "handlerId" integer,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "user_blocks" (
        "id" SERIAL PRIMARY KEY,
        "blockerId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "blockedId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_user_blocks_pair" UNIQUE ("blockerId", "blockedId")
      )`,
      `CREATE TABLE "verification_requests" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "realName" varchar NOT NULL,
        "idCardFrontUrl" varchar NOT NULL DEFAULT '',
        "idCardBackUrl" varchar NOT NULL DEFAULT '',
        "selfieUrl" varchar NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT 'pending',
        "reviewNote" text NOT NULL DEFAULT '',
        "reviewerId" integer,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "ai_delegate_profiles" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
        "enabled" boolean NOT NULL DEFAULT false,
        "allowDiscovery" boolean NOT NULL DEFAULT false,
        "allowAutoIntro" boolean NOT NULL DEFAULT false,
        "maxDailyIntros" integer NOT NULL DEFAULT 3,
        "tone" varchar NOT NULL DEFAULT '',
        "city" varchar NOT NULL DEFAULT '',
        "interestTags" text NOT NULL DEFAULT '',
        "bio" text NOT NULL DEFAULT '',
        "lookingFor" text NOT NULL DEFAULT '',
        "boundaries" text NOT NULL DEFAULT '',
        "openingLine" text NOT NULL DEFAULT '',
        "safetyNote" text NOT NULL DEFAULT '',
        "status" varchar NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "ai_match_sessions" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "targetUserId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "score" integer NOT NULL DEFAULT 0,
        "status" varchar NOT NULL DEFAULT 'review',
        "source" varchar NOT NULL DEFAULT 'manual',
        "mode" varchar NOT NULL DEFAULT 'ai_delegate',
        "conversationId" varchar,
        "introSent" boolean NOT NULL DEFAULT false,
        "introSentAt" timestamp,
        "reason" text NOT NULL DEFAULT '',
        "commonTags" text NOT NULL DEFAULT '',
        "metadata" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "waitlist_app_entries" (
        "id" SERIAL PRIMARY KEY,
        "email" varchar(160) NOT NULL UNIQUE,
        "phone" varchar(40),
        "name" varchar(80) NOT NULL DEFAULT '',
        "city" varchar(80) NOT NULL DEFAULT '',
        "inviteCode" varchar(80) NOT NULL DEFAULT '',
        "locale" varchar(20) NOT NULL DEFAULT 'zh-CN',
        "timezone" varchar(80) NOT NULL DEFAULT 'Asia/Shanghai',
        "deviceType" varchar(16) NOT NULL,
        "interestTags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "goals" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "source" varchar(32) NOT NULL,
        "marketingOptIn" boolean NOT NULL DEFAULT false,
        "ipHash" varchar(64),
        "entryPoint" varchar(80) NOT NULL DEFAULT 'app_page',
        "score" integer NOT NULL DEFAULT 0,
        "qualityLevel" varchar(16) NOT NULL DEFAULT 'low',
        "riskFlags" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "status" varchar(24) NOT NULL DEFAULT 'pending',
        "notes" varchar(96) NOT NULL DEFAULT '',
        "adminNote" text NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "invite_codes" (
        "id" SERIAL PRIMARY KEY,
        "code" varchar(64) NOT NULL UNIQUE,
        "batchName" varchar(120) NOT NULL DEFAULT '',
        "channel" varchar(80) NOT NULL DEFAULT '',
        "createdBy" varchar(80) NOT NULL DEFAULT '',
        "note" varchar(120) NOT NULL DEFAULT '',
        "maxUses" integer NOT NULL DEFAULT 1,
        "usedCount" integer NOT NULL DEFAULT 0,
        "active" boolean NOT NULL DEFAULT true,
        "expiresAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "waitlist_analytics_events" (
        "id" SERIAL PRIMARY KEY,
        "eventName" varchar(80) NOT NULL,
        "ipHash" varchar(96) NOT NULL DEFAULT '',
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "admin_roles" (
        "id" SERIAL PRIMARY KEY,
        "key" varchar(80) NOT NULL UNIQUE,
        "name" varchar(120) NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "admin_permissions" (
        "id" SERIAL PRIMARY KEY,
        "key" varchar(120) NOT NULL UNIQUE,
        "description" text NOT NULL DEFAULT '',
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "admin_user_roles" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "roleKey" varchar(80) NOT NULL,
        "grantedByUserId" integer,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_admin_user_roles_user_role" UNIQUE ("userId", "roleKey")
      )`,
      `CREATE TABLE "admin_audit_logs" (
        "id" SERIAL PRIMARY KEY,
        "userId" integer,
        "permission" varchar(120),
        "action" varchar(240) NOT NULL DEFAULT '',
        "status" varchar(40) NOT NULL,
        "reason" text NOT NULL DEFAULT '',
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_reflection_runs" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer,
        "agentTaskId" integer,
        "triggerType" varchar(80) NOT NULL DEFAULT 'quality_failed',
        "status" varchar(40) NOT NULL DEFAULT 'queued',
        "source" varchar(80) NOT NULL DEFAULT 'fitmeet_agent',
        "severity" varchar(20) NOT NULL DEFAULT 'medium',
        "qualityScore" integer,
        "failedChecks" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "input" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "reflection" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "suggestedPatchIds" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "completedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_skill_patches" (
        "id" SERIAL PRIMARY KEY,
        "reflectionRunId" integer,
        "patchType" varchar(60) NOT NULL,
        "status" varchar(40) NOT NULL DEFAULT 'draft',
        "riskLevel" varchar(20) NOT NULL DEFAULT 'medium',
        "title" varchar(160) NOT NULL,
        "rationale" text NOT NULL DEFAULT '',
        "target" varchar(160) NOT NULL DEFAULT '',
        "patch" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "evalCaseIds" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "reviewedByUserId" integer,
        "reviewedAt" timestamptz,
        "publishedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_eval_cases" (
        "id" SERIAL PRIMARY KEY,
        "reflectionRunId" integer,
        "agentTaskId" integer,
        "caseType" varchar(80) NOT NULL DEFAULT 'quality_regression',
        "status" varchar(40) NOT NULL DEFAULT 'active',
        "title" varchar(160) NOT NULL,
        "input" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "expectedBehavior" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "source" varchar(80) NOT NULL DEFAULT 'self_improve',
        "lastRun" jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_online_replay_samples" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer,
        "agentTaskId" integer,
        "evalCaseId" integer,
        "replayType" varchar(80) NOT NULL DEFAULT 'chat_turn',
        "status" varchar(40) NOT NULL DEFAULT 'captured',
        "input" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "expectedBehavior" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "replayContext" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "lastReplay" jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_subagent_memory" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL,
        "agentTaskId" integer,
        "agentName" varchar(80) NOT NULL,
        "memoryScope" varchar(120) NOT NULL,
        "input" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "observation" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "critique" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "handoffOutput" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_meet_loop_states" (
        "id" SERIAL PRIMARY KEY,
        "ownerUserId" integer NOT NULL,
        "agentTaskId" integer NOT NULL UNIQUE,
        "activityId" integer,
        "candidateUserId" integer,
        "stage" varchar(80) NOT NULL DEFAULT 'draft_created',
        "waitingFor" varchar(80) NOT NULL DEFAULT 'waiting_confirmation',
        "state" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "transitionHistory" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "review" jsonb,
        "completedAt" timestamptz,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "agent_skill_patch_effects" (
        "id" SERIAL PRIMARY KEY,
        "patchId" integer NOT NULL,
        "metric" varchar(80) NOT NULL,
        "value" double precision NOT NULL,
        "sampleSize" integer,
        "decision" varchar(40) NOT NULL DEFAULT 'observe',
        "note" text NOT NULL DEFAULT '',
        "context" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "subagent_worker_jobs" (
        "id" SERIAL PRIMARY KEY,
        "agentName" varchar(80) NOT NULL,
        "queueName" varchar(120) NOT NULL,
        "status" varchar(40) NOT NULL DEFAULT 'queued',
        "priority" integer NOT NULL DEFAULT 0,
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "result" jsonb,
        "attempts" integer NOT NULL DEFAULT 0,
        "maxAttempts" integer NOT NULL DEFAULT 3,
        "lockedBy" varchar(160),
        "lockedUntil" timestamptz,
        "runId" varchar(96),
        "traceId" varchar(96),
        "lastError" text,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE "subagent_worker_heartbeats" (
        "id" SERIAL PRIMARY KEY,
        "workerId" varchar(160) NOT NULL,
        "queueName" varchar(120) NOT NULL,
        "status" varchar(40) NOT NULL DEFAULT 'idle',
        "activeJobId" integer,
        "lastSeenAt" timestamptz NOT NULL,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_subagent_worker_heartbeats_worker_queue" UNIQUE ("workerId", "queueName")
      )`,
      `CREATE TABLE "subagent_worker_failures" (
        "id" SERIAL PRIMARY KEY,
        "jobId" integer NOT NULL,
        "agentName" varchar(80) NOT NULL,
        "queueName" varchar(120) NOT NULL,
        "workerId" varchar(160),
        "error" text NOT NULL,
        "context" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" timestamptz NOT NULL DEFAULT now()
      )`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "fieldValue" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "confirmedByUser" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "revoked" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "lastInferredAt" timestamptz`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "signalType" varchar(40) NOT NULL DEFAULT 'core'`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "visibleInRecommendationReason" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "userCanDisableForMatching" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "life_graph_fields" ADD COLUMN IF NOT EXISTS "enabledForMatching" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "completenessScore" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "currentSocialGoal" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "aiSummary" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "preferredLanguage" varchar NOT NULL DEFAULT 'zh-CN'`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "country" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "region" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_profiles" ADD COLUMN IF NOT EXISTS "lastUpdatedAt" timestamptz`,
      `ALTER TABLE "life_graph_proposals" ADD COLUMN IF NOT EXISTS "taskId" integer`,
      `ALTER TABLE "life_graph_proposals" ADD COLUMN IF NOT EXISTS "messageId" varchar(96)`,
      `ALTER TABLE "life_graph_proposals" ADD COLUMN IF NOT EXISTS "proposedFields" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "life_graph_proposals" ADD COLUMN IF NOT EXISTS "missingFields" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "life_graph_proposals" ADD COLUMN IF NOT EXISTS "confirmationRequired" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "life_graph_audit_logs" ADD COLUMN IF NOT EXISTS "oldValue" jsonb`,
      `ALTER TABLE "life_graph_audit_logs" ADD COLUMN IF NOT EXISTS "newValue" jsonb`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "before" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "after" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "userFacingSummary" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "reversible" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "eventId" integer`,
      `ALTER TABLE "life_graph_update_audits" ADD COLUMN IF NOT EXISTS "correctionId" integer`,
      `ALTER TABLE "life_graph_events" ADD COLUMN IF NOT EXISTS "naturalSummary" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_corrections" ADD COLUMN IF NOT EXISTS "correctionType" varchar(48) NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_corrections" ADD COLUMN IF NOT EXISTS "previousValue" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "life_graph_corrections" ADD COLUMN IF NOT EXISTS "correctedValue" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "life_graph_signal_scores" ADD COLUMN IF NOT EXISTS "enabledForMatching" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "life_graph_signal_scores" ADD COLUMN IF NOT EXISTS "correctionCount" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "life_graph_signal_scores" ADD COLUMN IF NOT EXISTS "lastCalculatedAt" timestamptz`,
      `ALTER TABLE "life_graph_access_audit_logs" ADD COLUMN IF NOT EXISTS "route" varchar(120) NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_access_audit_logs" ADD COLUMN IF NOT EXISTS "dataTiers" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "life_graph_security_requests" ADD COLUMN IF NOT EXISTS "requestedByUserId" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "life_graph_security_requests" ADD COLUMN IF NOT EXISTS "confirmationCodeHash" varchar(128) NOT NULL DEFAULT ''`,
      `ALTER TABLE "life_graph_security_requests" ADD COLUMN IF NOT EXISTS "executedAt" timestamptz`,
      `ALTER TABLE "life_graph_security_requests" ADD COLUMN IF NOT EXISTS "notificationEmail" varchar(160)`,
      `ALTER TABLE "life_graph_security_requests" ADD COLUMN IF NOT EXISTS "notificationStatus" varchar(40) NOT NULL DEFAULT 'skipped'`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "privacyConsent" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "autoChatEnabled" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "dailyAutoChatLimit" integer NOT NULL DEFAULT 3`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "preferredName" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "favoriteSports" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "workExperience" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "idealPartner" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "ai_delegate_profiles" ADD COLUMN IF NOT EXISTS "trainingGoals" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "ai_match_sessions" ADD COLUMN IF NOT EXISTS "ownerId" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "ai_match_sessions" ADD COLUMN IF NOT EXISTS "initiatedBy" varchar NOT NULL DEFAULT 'manual'`,
      `ALTER TABLE "ai_match_sessions" ADD COLUMN IF NOT EXISTS "contactCardSent" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "ai_match_sessions" ADD COLUMN IF NOT EXISTS "contactedAt" timestamp`,
      `ALTER TABLE "ai_match_sessions" ADD COLUMN IF NOT EXISTS "transcript" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "matchedCandidateId" integer`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "startTime" timestamp`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "endTime" timestamp`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "icebreakerTasks" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "proofRequired" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "checkinByUserId" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "confirmByUserId" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "reviewByUserId" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_activities" ADD COLUMN IF NOT EXISTS "recap" text`,
      `ALTER TABLE "activity_proofs" ADD COLUMN IF NOT EXISTS "reviewedById" integer`,
      `ALTER TABLE "activity_proofs" ADD COLUMN IF NOT EXISTS "reviewReason" varchar(500) NOT NULL DEFAULT ''`,
      `ALTER TABLE "activity_templates" ADD COLUMN IF NOT EXISTS "defaultIcebreakers" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "activity_templates" ADD COLUMN IF NOT EXISTS "proofOptions" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "emergency_contacts" ADD COLUMN IF NOT EXISTS "relation" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "safety_reports" ADD COLUMN IF NOT EXISTS "targetType" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "safety_reports" ADD COLUMN IF NOT EXISTS "targetId" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "safety_reports" ADD COLUMN IF NOT EXISTS "handledById" integer`,
      `ALTER TABLE "verification_requests" ADD COLUMN IF NOT EXISTS "idNumberMasked" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "verification_requests" ADD COLUMN IF NOT EXISTS "certName" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "verification_requests" ADD COLUMN IF NOT EXISTS "certImageUrl" varchar NOT NULL DEFAULT ''`,
      `ALTER TABLE "verification_requests" ADD COLUMN IF NOT EXISTS "handledById" integer`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "country" varchar(80) NOT NULL DEFAULT ''`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "region" varchar(80) NOT NULL DEFAULT ''`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "preferredLanguage" varchar(20) NOT NULL DEFAULT 'zh-CN'`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "scenarios" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "userRole" varchar(32) NOT NULL DEFAULT ''`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "interviewWilling" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "qualityScore" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "qualityReasons" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "waitlist_app_entries" ADD COLUMN IF NOT EXISTS "userAgent" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "invite_codes" ADD COLUMN IF NOT EXISTS "scenario" varchar(120) NOT NULL DEFAULT ''`,
      `ALTER TABLE "agent_task_events" ADD COLUMN IF NOT EXISTS "stepId" varchar(80)`,
      `ALTER TABLE "agent_task_events" ADD COLUMN IF NOT EXISTS "toolCallId" varchar(80)`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "approvalRequestId" integer`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "phase" varchar(80)`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "resumePrompt" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "state" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "steps" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "events" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "resumeCount" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "agent_run_checkpoints" ADD COLUMN IF NOT EXISTS "resumedAt" timestamptz`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "idealPartnerDescription" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "aestheticPreferences" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "personalityPreferences" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "privacyBoundaries" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "agentMessagingEnabled" boolean NOT NULL DEFAULT false`,
      `ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "acceptAgentMessages" boolean NOT NULL DEFAULT true`,
      `ALTER TABLE "agent_action_logs" ADD COLUMN IF NOT EXISTS "targetAgentId" integer`,
      `ALTER TABLE "agent_settings" ADD COLUMN IF NOT EXISTS "maxDailyMessages" integer NOT NULL DEFAULT 20`,
      `ALTER TABLE "payment_intents" ADD COLUMN IF NOT EXISTS "providerReference" varchar(120)`,
      `ALTER TABLE "social_agent_reminder_preferences" ADD COLUMN IF NOT EXISTS "lastSuggestedAt" timestamptz`,
      `ALTER TABLE "social_agent_reminder_preferences" ADD COLUMN IF NOT EXISTS "mutedUntil" timestamptz`,
      `ALTER TABLE "social_agent_reminders" ADD COLUMN IF NOT EXISTS "topic" varchar(40) NOT NULL DEFAULT 'suggested'`,
      `ALTER TABLE "social_agent_reminders" ADD COLUMN IF NOT EXISTS "message" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "social_agent_reminders" ADD COLUMN IF NOT EXISTS "context" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_agent_reminders" ADD COLUMN IF NOT EXISTS "threadId" varchar(120)`,
      `ALTER TABLE "social_agent_reminders" ADD COLUMN IF NOT EXISTS "dismissedAt" timestamptz`,
      `ALTER TABLE "agent_activity_logs" ADD COLUMN IF NOT EXISTS "blockReason" text`,
      `ALTER TABLE "social_agent_long_term_memory" ADD COLUMN IF NOT EXISTS "preferences" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_agent_long_term_memory" ADD COLUMN IF NOT EXISTS "activityPreferences" jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ALTER TABLE "social_agent_long_term_memory" ADD COLUMN IF NOT EXISTS "taskSummaries" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "social_agent_long_term_memory" ADD COLUMN IF NOT EXISTS "taskCount" integer NOT NULL DEFAULT 0`,
      `ALTER TABLE "social_agent_user_interest_events" ADD COLUMN IF NOT EXISTS "candidateRecordId" integer`,
      `ALTER TABLE "social_agent_user_interest_events" ADD COLUMN IF NOT EXISTS "activityTags" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "social_agent_user_interest_events" ADD COLUMN IF NOT EXISTS "candidatePreferenceTags" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "social_agent_user_interest_events" ADD COLUMN IF NOT EXISTS "locationText" varchar(160)`,
      `ALTER TABLE "social_agent_user_interest_events" ADD COLUMN IF NOT EXISTS "timeWindow" varchar(120)`,
      `ALTER TABLE "match_candidates" ADD COLUMN IF NOT EXISTS "reasonTags" jsonb NOT NULL DEFAULT '[]'::jsonb`,
      `ALTER TABLE "match_candidates" ADD COLUMN IF NOT EXISTS "reasonText" text NOT NULL DEFAULT ''`,
      `ALTER TABLE "match_candidates" ADD COLUMN IF NOT EXISTS "userFeedback" text`,
      `CREATE INDEX "idx_user_social_requests_user_status" ON "user_social_requests" ("userId", "status")`,
      `CREATE INDEX "idx_user_social_requests_city_status" ON "user_social_requests" ("city", "status")`,
      `CREATE INDEX "idx_public_social_intents_user_status" ON "public_social_intents" ("userId", "status")`,
      `CREATE INDEX "idx_public_social_intents_linked_request" ON "public_social_intents" ("linkedSocialRequestId")`,
      `CREATE INDEX "idx_social_request_candidates_request_status" ON "social_request_candidates" ("socialRequestId", "status")`,
      `CREATE INDEX "idx_social_request_candidates_request_score" ON "social_request_candidates" ("socialRequestId", "score")`,
      `CREATE INDEX "idx_agent_tasks_owner_status_updated" ON "agent_tasks" ("ownerUserId", "status", "updatedAt")`,
      `CREATE UNIQUE INDEX "uniq_agent_tasks_idempotency_key" ON "agent_tasks" ("idempotencyKey") WHERE "idempotencyKey" IS NOT NULL`,
      `CREATE INDEX "idx_agent_task_events_task_created" ON "agent_task_events" ("taskId", "createdAt")`,
      `CREATE INDEX "idx_agent_approvals_task" ON "agent_approval_requests" ("agentTaskId")`,
      `CREATE UNIQUE INDEX "idx_agent_side_effect_action_key" ON "agent_side_effect_ledger" ("actionType", "idempotencyKey")`,
      `CREATE INDEX "idx_agent_side_effect_owner_task" ON "agent_side_effect_ledger" ("ownerUserId", "agentTaskId")`,
      `CREATE INDEX "idx_agent_side_effect_status_retry" ON "agent_side_effect_ledger" ("status", "nextRetryAt")`,
      `CREATE INDEX "idx_agent_action_logs_owner_created" ON "agent_action_logs" ("ownerUserId", "createdAt")`,
      `CREATE INDEX "idx_life_graph_fields_user_category" ON "life_graph_fields" ("userId", "category")`,
      `CREATE INDEX "idx_social_activities_city_status" ON "social_activities" ("city", "status")`,
      `CREATE INDEX "idx_waitlist_entries_status_created" ON "waitlist_app_entries" ("status", "createdAt")`,
    ];

    for (const statement of statements) {
      await queryRunner.query(statement);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const tables = [
      'admin_audit_logs',
      'admin_user_roles',
      'admin_permissions',
      'admin_roles',
      'subagent_worker_failures',
      'subagent_worker_heartbeats',
      'subagent_worker_jobs',
      'agent_skill_patch_effects',
      'agent_meet_loop_states',
      'agent_subagent_memory',
      'agent_online_replay_samples',
      'agent_eval_cases',
      'agent_skill_patches',
      'agent_reflection_runs',
      'waitlist_analytics_events',
      'invite_codes',
      'waitlist_app_entries',
      'ai_match_sessions',
      'ai_delegate_profiles',
      'verification_requests',
      'user_blocks',
      'safety_reports',
      'emergency_contacts',
      'payment_intents',
      'contact_requests',
      'safety_events',
      'activity_templates',
      'activity_proofs',
      'social_activities',
      'life_graph_access_audit_logs',
      'life_graph_security_requests',
      'life_graph_update_audits',
      'life_graph_signal_scores',
      'life_graph_corrections',
      'life_graph_events',
      'life_graph_audit_logs',
      'life_graph_proposals',
      'life_graph_fields',
      'life_graph_profiles',
      'social_agent_user_interest_events',
      'social_agent_reminders',
      'social_agent_reminder_preferences',
      'social_agent_message_feedback',
      'social_agent_long_term_memory',
      'agent_action_logs',
      'agent_activity_logs',
      'agent_memory_updates',
      'agent_messages',
      'agent_tool_calls',
      'agent_run_steps',
      'agent_runs',
      'agent_approval_requests',
      'agent_side_effect_ledger',
      'agent_run_checkpoints',
      'agent_task_events',
      'agent_tasks',
      'match_candidates',
      'public_social_intents',
      'social_requests',
      'social_request_candidates',
      'user_social_requests',
      'user_preferences',
      'agent_settings',
      'agent_permissions',
      'agent_profiles',
      'agent_connections',
      'meet_participants',
      'meets',
      'follows',
      'user_social_profiles',
      'users',
    ];

    for (const table of tables) {
      await queryRunner.query(`DROP TABLE IF EXISTS "${table}" CASCADE`);
    }
  }
}
