import type { AgentFlowPhase, AgentFlowPhaseConfig } from './agentFlow.types';

export const AGENT_FLOW_INTERESTS = ['咖啡', 'Citywalk', '散步', '轻聊天'] as const;

export const AGENT_FLOW_PHASE_CONFIG: Record<AgentFlowPhase, AgentFlowPhaseConfig> = {
  welcome: {
    antState: 'idle',
    antTarget: 'input',
    title: '我在这里',
    description: '可以直接提问，我会先按普通对话回应。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['focusInput', 'submitGoal'],
  },
  inputFocused: {
    antState: 'idle',
    antTarget: 'input',
    title: '随时输入',
    description: '可以闲聊、提问，也可以描述一个想完成的任务。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['submitGoal', 'reset'],
  },
  userSubmitted: {
    antState: 'thinking',
    antTarget: 'input',
    title: '我正在理解你的想法',
    description: '我会先理解语境，再用自然的方式回复。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['startAnalysis'],
  },
  analyzingIntent: {
    antState: 'thinking',
    antTarget: 'input',
    title: '我正在理解你的想法',
    description: '我正在整理上下文和回答重点。',
    recommendedDuration: 900,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['discoverScenes'],
  },
  discoveringScenes: {
    antState: 'discovering',
    antTarget: 'recommendation',
    title: '正在发现附近场景',
    description: '优先寻找更自然、更容易开口的社交机会。',
    recommendedDuration: 1300,
    rightPanelState: 'loadingRecommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['showRecommendations', 'showSafetyReminder'],
  },
  recommendationsReady: {
    antState: 'recommending',
    antTarget: 'recommendation',
    title: '我找到了一些建议',
    description: '这些场景更适合轻松破冰和持续交流。',
    recommendedDuration: 0,
    rightPanelState: 'recommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['generateOpener', 'requestConfirmation', 'showSafetyReminder', 'reset'],
  },
  generatingOpener: {
    antState: 'thinking',
    antTarget: 'recommendation',
    title: '我正在理解你的想法',
    description: '我会把表达整理得自然一些，确认前不会替你发送。',
    recommendedDuration: 900,
    rightPanelState: 'recommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['regenerateOpener'],
  },
  openerReady: {
    antState: 'success',
    antTarget: null,
    title: '完成了',
    description: '我已经为你准备好下一步建议。',
    recommendedDuration: 0,
    rightPanelState: 'recommendations',
    safetyCardVisible: true,
    confirmCardVisible: false,
    nextAllowedActions: ['requestConfirmation', 'regenerateOpener', 'showSafetyReminder'],
  },
  safetyReminder: {
    antState: 'reminding',
    antTarget: 'safetyCard',
    title: '先保护好边界',
    description: '建议先站内聊几句，第一次见面优先选择公共场所。',
    recommendedDuration: 0,
    rightPanelState: 'safety',
    safetyCardVisible: true,
    confirmCardVisible: false,
    nextAllowedActions: ['generateOpener', 'requestConfirmation', 'reset'],
  },
  awaitingConfirmation: {
    antState: 'confirming',
    antTarget: 'confirmButton',
    title: '需要你确认一下',
    description: '确认后我再帮你执行下一步。',
    recommendedDuration: 0,
    rightPanelState: 'confirmation',
    safetyCardVisible: true,
    confirmCardVisible: true,
    nextAllowedActions: ['confirmAction', 'regenerateOpener', 'showSafetyReminder'],
  },
  completed: {
    antState: 'success',
    antTarget: null,
    title: '已经回复',
    description: '可以继续追问，或告诉我下一步想做什么。',
    recommendedDuration: 0,
    rightPanelState: 'completed',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['reset'],
  },
  missingInfo: {
    antState: 'error',
    antTarget: 'input',
    title: '先输入一句话',
    description: '可以直接问我一个问题，或描述你现在想完成的事。',
    recommendedDuration: 0,
    rightPanelState: 'error',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['focusInput', 'submitGoal', 'reset'],
  },
  failed: {
    antState: 'error',
    antTarget: 'input',
    title: '这次没处理好',
    description: '可以换个说法再试一次，我会继续从当前上下文接上。',
    recommendedDuration: 0,
    rightPanelState: 'error',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['retry', 'reset'],
  },
};

export function getAgentFlowPhaseConfig(phase: AgentFlowPhase) {
  return AGENT_FLOW_PHASE_CONFIG[phase];
}
