import type { AgentFlowPhase, AgentFlowPhaseConfig } from './agentFlow.types';

export const AGENT_FLOW_INTERESTS = ['咖啡', 'Citywalk', '散步', '轻聊天'] as const;

export const AGENT_FLOW_PHASE_CONFIG: Record<AgentFlowPhase, AgentFlowPhaseConfig> = {
  welcome: {
    antState: 'idle',
    antTarget: 'input',
    title: '今天想认识什么样的人？',
    description: '从一个兴趣开始，我来帮你发现合适的人。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['focusInput', 'submitGoal'],
  },
  inputFocused: {
    antState: 'idle',
    antTarget: 'input',
    title: '今天想认识什么样的人？',
    description: '从一个兴趣开始，我来帮你发现合适的人。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['submitGoal', 'reset'],
  },
  userSubmitted: {
    antState: 'thinking',
    antTarget: 'input',
    title: '我正在理解你的想法',
    description: '我会结合兴趣、城市和当前场景生成建议。',
    recommendedDuration: 0,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['startAnalysis'],
  },
  analyzingIntent: {
    antState: 'thinking',
    antTarget: 'input',
    title: '我正在理解你的想法',
    description: '我会结合兴趣、城市和当前场景生成建议。',
    recommendedDuration: 900,
    rightPanelState: 'empty',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['discoverScenes'],
  },
  discoveringScenes: {
    antState: 'discovering',
    antTarget: 'recommendation',
    title: '正在发现附近场景',
    description: '优先寻找更自然、更容易开口的社交机会。',
    recommendedDuration: 1300,
    rightPanelState: 'loadingRecommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['showRecommendations', 'showSafetyReminder'],
  },
  recommendationsReady: {
    antState: 'recommending',
    antTarget: 'recommendation',
    title: '我找到了一些建议',
    description: '这些场景更适合轻松破冰和持续交流。',
    recommendedDuration: 0,
    rightPanelState: 'recommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['generateOpener', 'requestConfirmation', 'showSafetyReminder', 'reset'],
  },
  generatingOpener: {
    antState: 'thinking',
    antTarget: 'recommendation',
    title: '我正在理解你的想法',
    description: '我会结合兴趣、城市和当前场景生成建议。',
    recommendedDuration: 900,
    rightPanelState: 'recommendations',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['regenerateOpener'],
  },
  openerReady: {
    antState: 'success',
    antTarget: null,
    title: '完成了',
    description: '我已经为你准备好下一步建议。',
    recommendedDuration: 0,
    rightPanelState: 'recommendations',
    safetyCardVisible: true,
    confirmCardVisible: false,
    nextAllowedActions: ['requestConfirmation', 'regenerateOpener', 'showSafetyReminder'],
  },
  safetyReminder: {
    antState: 'reminding',
    antTarget: 'safetyCard',
    title: '先保护好边界',
    description: '建议先站内聊几句，第一次见面优先选择公共场所。',
    recommendedDuration: 0,
    rightPanelState: 'safety',
    safetyCardVisible: true,
    confirmCardVisible: false,
    nextAllowedActions: ['generateOpener', 'requestConfirmation', 'reset'],
  },
  awaitingConfirmation: {
    antState: 'confirming',
    antTarget: 'confirmButton',
    title: '需要你确认一下',
    description: '确认后我再帮你执行下一步。',
    recommendedDuration: 0,
    rightPanelState: 'confirmation',
    safetyCardVisible: true,
    confirmCardVisible: true,
    nextAllowedActions: ['confirmAction', 'regenerateOpener', 'showSafetyReminder'],
  },
  completed: {
    antState: 'success',
    antTarget: null,
    title: '完成了',
    description: '我已经为你准备好下一步建议。',
    recommendedDuration: 0,
    rightPanelState: 'completed',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['reset'],
  },
  missingInfo: {
    antState: 'error',
    antTarget: 'input',
    title: '还差一点信息',
    description: '告诉我你的兴趣、城市或想认识什么样的人，我才能继续。',
    recommendedDuration: 0,
    rightPanelState: 'error',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['focusInput', 'submitGoal', 'reset'],
  },
  failed: {
    antState: 'error',
    antTarget: 'input',
    title: '还差一点信息',
    description: '告诉我你的兴趣、城市或想认识什么样的人，我才能继续。',
    recommendedDuration: 0,
    rightPanelState: 'error',
    safetyCardVisible: false,
    confirmCardVisible: false,
    nextAllowedActions: ['retry', 'reset'],
  },
};

export function getAgentFlowPhaseConfig(phase: AgentFlowPhase) {
  return AGENT_FLOW_PHASE_CONFIG[phase];
}
